name: rtlapena
description: "R.T. Lapeña Construction & Supply Daily Time Record App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.12.0
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  signature: ^5.5.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
